baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "models-bulimov-ru"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Alexander Bulimov's Models"
  subtitle    = "Personal gallery"

  cover       = "images/bench_28_1920.jpg"

  description = "Just a small collection of scale models I've built."
  metaDescription = ""
  googleAnalytics = "UA-113451260-1"
  customCSS = []
  RSSLink = ""

  fbName = "abulimov"
  githubName = "abulimov"
  redditName = "abulimov"
  scalematesID = 38867

  # logo = "hugo-logo.png"
  orgName = "Alexander Bulimov"
  orgWebsite = "http://bulimov.ru"

  author = "Alexander Bulimov"
  authorAvatar = "/images/pixel.png"
  authorLocation = "Dublin, Ireland"
  authorWebsite = "https://bulimov.ru"
  authorDescription = "Amateur modelist"
  copyright = '<br/><small><small>  <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="//i.creativecommons.org/l/by-sa/4.0/80x15.png"></a>
      Content licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>, except where indicated otherwise.
        </small></small>'

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/models/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 100

[[menu.main]]
  name = "Airplanes"
  url = "/categories/airplanes/"
  weight = 99

[[menu.main]]
  name = "Ships"
  url = "/categories/ships/"
  weight = 98

[[menu.main]]
  name = "Vehicles"
  url = "/categories/vehicles/"
  weight = 97

[[menu.main]]
  name = "IT Blog"
  url = "http://bulimov.ru/"
  weight = 95
